### PR TITLE
V1.5update

### PR DESCRIPTION
**Pull request by mart-r**
Update medcat dependency as well as installed medcat version to 1.5.

As best I could tell, everything else should still work.

This should also fix issues with github action failures since 1.5 fixes the issues.

### CODE REVIEW

**Review by baixiac — APPROVED** [review]
LGTM

**Comment by baixiac** [comment]
Feel free to go ahead and merge this in.

**Comment by mart-r** [comment]
> ### This branch has no conflicts with the base branch
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

Would if I could:
> This branch has no conflicts with the base branch
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by baixiac** [comment]
Hi @antsh3k. Can you add @mart-r as a collaborator? Thanks.

**Pull request merged**
