### PR TITLE
CU-2vzhd93 Move logging tutorials from MedCAT to MedCATtutorials

### PR DESCRIPTION
**Pull request by mart-r**
Move tutorial regarding logging from MedCAT to MedCATtutorials.

So moved the files here.

Made sure to install MedCAT v1.4.0.

MedCAT PR In parallel:
https://github.com/CogStack/MedCAT/pull/273

### CODE REVIEW

**Comment by baixiac** [comment]
Hi, @mart-r, not sure if you saw the above comment. Shall we get the branch merged?

**Comment by mart-r** [comment]
Yeah, I saw it. But wanted to discuss with Tom regarding the numbering and stuff like that. I'll be adding a commit or two to address the following:
- Make this an optional tutorial (i.e change title)
- Make it Part 1.1

**Comment by baixiac** [comment]
Alright, looks like the CI is hitting the known `sklearn` issue.

**Comment by baixiac** [comment]
Hi, @mart-r . Given MedCAT 1.5.0 was released last week, do you mind upgrading `pip install` across those tutorials?

**Comment by mart-r** [comment]
> Hi, @mart-r . Given MedCAT 1.5.0 was released last week, do you mind upgrading `pip install` across those tutorials?

Yep, that's the next thing on my agenda. But I'll try and verify that everything works in the current form as I do it.

**Pull request merged**
