### PR TITLE
MetaCAT BERT update to tutorials 4.1 and 4.2

### PR DESCRIPTION
**Pull request by shubham-s-agarwal**
Updates to Tutorials 4.1 and 4.2: Integration of BERT Implementation

- Tutorial 4.1: No changes were necessary since BERT utilizes its own pre-trained tokenizer. A note has been added advising users to proceed directly to Tutorial 4.2 if using BERT.

- Tutorial 4.2: BERT implementation has been added, showing training on the given dataset. Unlike BiLSTM, which fine-tunes a previously trained model pack, BERT is trained from scratch.

### CODE REVIEW

**Review by mart-r — CHANGES_REQUESTED** [review]
4.1 looks good. Don't think there needs to be more in here for that.

4.2
- The `MetaCAT configuration` and the `Train MetaCAT` (sub)section are now duplicated. It would be good to have these appear once. Otherwise we'll end up having to maintain 2 copies of the same text/code.
The two MetaCAT instances (BERT vs BiLSTM) should provide the exact same interface anyway. The only difference is that some config entries don't affect one or the other.
- Perhaps we can trim the included output a little? I know it's already long in the existing one, but just doing this comparison it was pretty annoying to have to scroll around the sizeable chunks of output.

**Comment by shubham-s-agarwal** [comment]
For 4.2:

- `MetaCAT configuration` and the `Train MetaCAT ` and subsections for BERT and Bi-LSTM in them.
- Since `model_variant` isn't commonly changed, I haven't added it in the tutorial. There is a link to all config options.
- For the config section for BERT, we have to explicitly change the model_name, category_name and other variables since we are starting the training from scratch. For Bi-LSTM, we are loading the model pack; if we were training Bi-LSTM from scratch, we would have the do the same.

**Review by mart-r — CHANGES_REQUESTED** [review]
> * Since `model_variant` isn't commonly changed, I haven't added it in the tutorial. There is a link to all config variables in the section.

But you're using it in the tutorial - passing it to `TokenizerWrapperBERT.load`. Someone going through the tutorial won't have any idea what this is or what value it holds.


In 4.2 I don't think we need 2 different (almost identical) `mc.train_from_json` code blocks. We could just have 1 and get the suffix for the save file from `config_metacat.model.model_name` automatically.

Other than that, I think this looks good.

**Review by mart-r — APPROVED** [review]
Thought I already approved yesterday, but I think I was waiting for GHA workflow just in case.

Looks good to me.

**Pull request merged**
